title: Rahul Yadav # your name (or website title) here
logo: "/images/github-pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I'm Rahul -Â Programmer, Machine Learning Addict, perpetually curious and obsessed with changing the world for the better (Mildly political too)

  <a href="https://www.linkedin.com/in/rahulynot/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
